version: 2

sources:
  - name: tpch_samples
    description: This is a replica of the Postgres database used by our app
    database: samples
    schema: tpch
    tables:
      - name: lineitem
        columns:
          - name: l_orderkey
            data_type: bigint
          - name: l_partkey
            data_type: bigint
          - name: l_suppkey
            data_type: bigint
          - name: l_linenumber
            data_type: int
          - name: l_quantity
            data_type: decimal(18,2)
          - name: l_extendedprice
            data_type: decimal(18,2)
          - name: l_discount
            data_type: decimal(18,2)
          - name: l_tax
            data_type: decimal(18,2)
          - name: l_returnflag
            data_type: string
          - name: l_linestatus
            data_type: string
          - name: l_shipdate
            data_type: date
          - name: l_commitdate
            data_type: date
          - name: l_receiptdate
            data_type: date
          - name: l_shipinstruct
            data_type: string
          - name: l_shipmode
            data_type: string
          - name: l_comment
            data_type: string
      - name: orders
        columns:
          - name: o_orderkey
            data_type: bigint
          - name: o_custkey
            data_type: bigint
          - name: o_orderstatus
            data_type: string
          - name: o_totalprice
            data_type: decimal(18,2)
          - name: o_orderdate
            data_type: date
          - name: o_orderpriority
            data_type: string
          - name: o_clerk
            data_type: string
          - name: o_shippriority
            data_type: int
          - name: o_comment
            data_type: string
      - name: customer
        columns:
          - name: c_custkey
            data_type: bigint
          - name: c_name
            data_type: string
          - name: c_address
            data_type: string
          - name: c_nationkey
            data_type: bigint
          - name: c_phone
            data_type: string
          - name: c_acctbal
            data_type: decimal(18,2)
          - name: c_mktsegment
            data_type: string
          - name: c_comment
            data_type: string
      - name: nation
        columns:
          - name: n_nationkey
            data_type: bigint
          - name: n_name
            data_type: string
          - name: n_regionkey
            data_type: bigint
          - name: n_comment
            data_type: string